package server

import (
	"github.com/gin-gonic/gin"
	"github.com/swaggo/files"
	"github.com/swaggo/gin-swagger"
	
	"github.com/Oloruntobi1/walletservice/docs" // docs is generated by Swag CLI, you have to import it.
)

// @contact.name Tobi Balogun
// @contact.url blgntobi@gmail.com
// @contact.email blgntobi@gmail.com

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @termsOfService blgntobi@gmail.com

// @x-extension-openapi {"example": "value on a json format"}

type Server struct {
	router *gin.Engine
}

func NewServer() *Server{
	s := &Server{}
	docs.SwaggerInfo.Title = "Wallet API"
	docs.SwaggerInfo.Description = "This is a sample wallet service."
	docs.SwaggerInfo.Version = "1.0"
	docs.SwaggerInfo.Host = "localhost:8080"
	docs.SwaggerInfo.BasePath = "/"
	docs.SwaggerInfo.Schemes = []string{"http", "https"}
	r := gin.Default()
	
	r.POST("/createwallet", s.HandleWalletCreate)
	r.POST("/payout", s.HandlePayout)
	
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	s.router = r
	return s
}

func(s *Server) Start(add string) error {
	return s.router.Run(add)
} 

